runtime: python312  # Specify Python 3.12 as the runtime

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

# Optional instance settings
instance_class: F2

# Automatic scaling
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
